### ISSUE TITLE
x16 for large numbers

### ISSUE THREAD

**Issue by benibela** [non/spire#104]
The x16 prefix does not work for large numbers. E.g:

scala> x16"ABABABAB"
error: exception during macro expansion: 
java.lang.NumberFormatException: For input string: "ABABABAB"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:495)
    at spire.macrosk.Macros$.radix(Macros.scala:228)

**Comment by denisrosset** [comment]
Closing this due to a long period of inactivity. Please consider opening a new issue or reopening this PR to restart discussion. We're very sorry for the possible inconvenience. See #674
