### ISSUE TITLE
exception in spire.example.RandomForestExample

### ISSUE THREAD

**Issue by epishkin** [non/spire#237]
```
sbt
project examples
run
//type 2 <Enter>
```

```
[info] Running spire.example.RandomForestExample

Iris - 150 points with 5 variables (4 effective):
     1. Sepal Length (continuous)
     2. Sepal Width (continuous)
     3. Petal Length (continuous)
     4. Petal Width (continuous)
     5. Species (ignored)

Cross-validating Iris with random forest classification...
[error] (run-main) java.lang.AbstractMethodError: spire.example.RandomForestExample$$anonfun$1.apply(Ljava/lang/Object;)Ljava/lang/Object;
java.lang.AbstractMethodError: spire.example.RandomForestExample$$anonfun$1.apply(Ljava/lang/Object;)Ljava/lang/Object;
	at spire.example.CrossValidation$.loop$1(DataSets.scala:234)
	at spire.example.CrossValidation$.crossValidate(DataSets.scala:242)
	at spire.example.CrossValidation$.crossValidateClassification(DataSets.scala:259)
	at spire.example.RandomForestExample$.testClassification(randomforest.scala:40)
	at spire.example.RandomForestExample$delayedInit$body.apply(randomforest.scala:24)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at spire.example.RandomForestExample$.main(randomforest.scala:21)
	at spire.example.RandomForestExample.main(randomforest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last examples/compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last examples/compile:run for the full output.
[error] (examples/compile:run) Nonzero exit code: 1
[error] Total time: 20 s, completed Mar 11, 2014 8:26:49 PM
```

**Comment by kevinmeredith** [comment]
On Scala 2.11.6, I was unable to reproduce this error. Also, the **RandomForest** option is, as of the current `master` branch, number 7.

```
Enter number: 7

[info] Running spire.example.RandomForestExample

Iris - 150 points with 5 variables (4 effective):
     1. Sepal Length (continuous)
     2. Sepal Width (continuous)
     3. Petal Length (continuous)
     4. Petal Width (continuous)
     5. Species (ignored)

Cross-validating Iris with random forest classification...
... accuracy of 94.67%


Yeast - 1484 points with 10 variables (8 effective):
     1. Protein (ignored)
     2. mcg (continuous)
     3. gvh (continuous)
     4. alm (continuous)
     5. mit (continuous)
     6. erl (continuous)
     7. pox (continuous)
     8. vac (continuous)
     9. nuc (continuous)
    10. Location (ignored)

Cross-validating Yeast with random forest classification...
... accuracy of 49.39%


MPG - 398 points with 9 variables (13 effective):
     1. MPG (ignored)
     2. # of Cylinders (categorical)
     3. Displacement (continuous)
     4. Horsepower (continuous with missing values)
     5. Weight (continuous)
     6. Acceleration (continuous)
     7. Model Year (continuous)
     8. Country of Origin (categorical)
     9. Model Name (ignored)

Cross-validating MPG with random forest regression...
... R^2 of 0.818
[success] Total time: 17 s, completed Apr 29, 2015 8:38:04 PM
```

**Comment by epishkin** [comment]
works now. I will close this issue.

**Comment by non** [comment]
Thanks!
