### ISSUE TITLE
initialization problem with OrderProduct

### ISSUE THREAD

**Issue by non** [non/spire#351]
Just today I got this NPE:

```
java.lang.NullPointerException
  at spire.std.OrderProduct2$mcDI$sp$class.compare$mcDI$sp(tuples.scala:5954)
  at spire.std.OrderProductInstances$$anon$167.compare$mcDI$sp(tuples.scala:7107)
  at spire.std.OrderProduct2$mcDI$sp$class.compare(tuples.scala:5953)
  at spire.std.OrderProductInstances$$anon$167.compare(tuples.scala:7107)
  at spire.std.OrderProductInstances$$anon$167.compare(tuples.scala:7107)
  at spire.algebra.Order$class.lt(Order.scala:29)
  at spire.std.OrderProductInstances$$anon$167.lt(tuples.scala:7107)
  at spire.math.HighBranchingMedianOf5$class.mo5(Selection.scala:162)
  at spire.math.QuickSelect$.mo5(Selection.scala:319)
  at spire.math.QuickSelect$.approxMedian(Selection.scala:333)
  at spire.math.SelectLike$class.select(Selection.scala:55)
  at spire.math.QuickSelect$.select(Selection.scala:319)
  at spire.math.SelectLike$class.select(Selection.scala:30)
  at spire.math.QuickSelect$.select(Selection.scala:319)
  at spire.math.Selection$.quickSelect(Selection.scala:355)
  at spire.math.Selection$.select(Selection.scala:349)
  at spire.syntax.std.ArrayOps.qselect(Ops.scala:179)
  ... 45 elided
```

Looks like there's an initialization order problem somewhere in `tuples.scala`.

**Comment by non** [comment]
Nevermind. User error, PEBKAC, etc.
