### ISSUE TITLE
Equals between PolySparse and PolyDense can throw exception

### ISSUE THREAD

**Issue by rklaehn** [non/spire#409]
```scala
scala> Polynomial("(0)") == Polynomial("(1)")
java.lang.ArrayIndexOutOfBoundsException: 0
  at spire.math.Polynomial$class.loop$3(Polynomial.scala:272)
  at spire.math.Polynomial$class.equals(Polynomial.scala:283)
  at spire.math.poly.PolySparse.equals(PolySparse.scala:17)
  ... 43 elided
```

**Comment by rklaehn** [comment]
I think this is because the zero polynomial has a coefficient array of size zero, so `lhs.degree == rhs.degree` is not sufficient to prevent an exception.

**Comment by kevinmeredith** [comment]
I could not reproduce this error:

```
scala> Polynomial("(0)") == Polynomial("(1)")
res1: Boolean = false
```

Perhaps the closed issue handled this one too?

**Comment by non** [comment]
Yes, I think we did get this fixed. Thanks for verifying it.
