### ISSUE TITLE
tests failing in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [non/spire#580]
```
[spire] [info] *** 21 TESTS FAILED ***
[spire] [error] Failed: Total 2327, Failed 21, Errors 0, Passed 2306
[spire] [error] Failed tests:
[spire] [error]     spire.math.prime.FactorsCheck
[spire] [error]     spire.laws.ArbTest
[spire] [error]     spire.laws.LawTests
[spire] [error] (testsJVM/test:test) sbt.TestsFailedException: Tests unsuccessful
```

that's from https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/648/consoleFull

**Comment by non** [comment]
Thanks @SethTisue, I'll take a look!

**Comment by SethTisue** [comment]
one that cropped up today:

```
[spire] [info] - rational/sparse p + 0 = p *** FAILED *** (122 milliseconds)
[spire] [info]   TestFailedException was thrown during property evaluation.
[spire] [info]     Message: (80/43x⁹⁵ + x⁹¹ + 1/4x⁸⁹ - 1/8x⁸⁴ - 34x⁸² + x⁸⁰ + 1/7x⁷⁸ - 52/7x⁷⁴ + 7/2x⁷³ + 7/54x⁷¹ - 1/53x⁶⁹ + 1/2x⁶⁸ + 1/8x⁶⁴ + 1/4x⁶¹ - 124/5x⁵³ - 4241/690x⁴⁸ - 37/30x⁴⁷ + 1/21x⁴² + x³⁸ + 29x³⁶ + x²³ + 36x²¹ - 13x¹⁹ - 229/520x¹⁶ + 43/35x¹¹ + 371/624x¹⁰ - 1062/217x⁹ + 33/46x³ + 69x² + 95015759/19888440x + 77125717/602140) was not equal to (80/43x⁹⁵ + x⁹¹ + 1/4x⁸⁹ - 1/8x⁸⁴ - 34x⁸² + x⁸⁰ + 1/7x⁷⁸ - 52/7x⁷⁴ + 7/2x⁷³ + 7/54x⁷¹ - 1/53x⁶⁹ + 1/2x⁶⁸ + 1/8x⁶⁴ + 1/4x⁶¹ - 124/5x⁵³ - 4241/690x⁴⁸ - 37/30x⁴⁷ + 1/21x⁴² + x³⁸ + 29x³⁶ + x²³ + 36x²¹ - 13x¹⁹ - 229/520x¹⁶ + 43/35x¹¹ + 371/624x¹⁰ - 1062/217x⁹ + 33/46x³ + 69x² + 95015759/19888440x + 77125717/602140)
[spire] [info]     Location: (PolynomialTest.scala:97)
[spire] [info]     Occurred when passed generated values (
[spire] [info]       arg0 = (80/43x⁹⁵ + x⁹¹ + 1/4x⁸⁹ - 1/8x⁸⁴ - 34x⁸² + x⁸⁰ + 1/7x⁷⁸ - 52/7x⁷⁴ + 7/2x⁷³ + 7/54x⁷¹ - 1/53x⁶⁹ + 1/2x⁶⁸ + 1/8x⁶⁴ + 1/4x⁶¹ - 124/5x⁵³ - 4241/690x⁴⁸ - 37/30x⁴⁷ + 1/21x⁴² + x³⁸ + 29x³⁶ + x²³ + 36x²¹ - 13x¹⁹ - 229/520x¹⁶ + 43/35x¹¹ + 371/624x¹⁰ - 1062/217x⁹ + 33/46x³ + 69x² + 95015759/19888440x + 77125717/602140)
[spire] [info]     )
[spire] [info]   org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException:
[spire] [info]   at org.scalatest.enablers.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:231)
[spire] [info]   at org.scalatest.enablers.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:219)
[spire] [info]   at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:158)
[spire] [info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll(GeneratorDrivenPropertyChecks.scala:851)
[spire] [info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll$(GeneratorDrivenPropertyChecks.scala:827)
[spire] [info]   at spire.math.PolynomialCheck.forAll(PolynomialTest.scala:53)
[spire] [info]   at spire.math.PolynomialCheck.$anonfun$runTest$3(PolynomialTest.scala:97)
[spire] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[spire] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[spire] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[spire] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[spire] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[spire] [info]   at org.scalatest.PropSpecLike$$anon$1.apply(PropSpecLike.scala:186)
[spire] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[spire] [info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[spire] [info]   at org.scalatest.PropSpec.withFixture(PropSpec.scala:874)
[spire] [info]   at org.scalatest.PropSpecLike.invokeWithFixture$1(PropSpecLike.scala:184)
[spire] [info]   at org.scalatest.PropSpecLike.$anonfun$runTest$1(PropSpecLike.scala:196)
[spire] [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[spire] [info]   at org.scalatest.PropSpecLike.runTest(PropSpecLike.scala:196)
[spire] [info]   at org.scalatest.PropSpecLike.runTest$(PropSpecLike.scala:178)
[spire] [info]   at org.scalatest.PropSpec.runTest(PropSpec.scala:874)
[spire] [info]   at org.scalatest.PropSpecLike.$anonfun$runTests$1(PropSpecLike.scala:229)
[spire] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[spire] [info]   at scala.collection.immutable.List.foreach(List.scala:378)
[spire] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[spire] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[spire] [info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[spire] [info]   at org.scalatest.PropSpecLike.runTests(PropSpecLike.scala:229)
[spire] [info]   at org.scalatest.PropSpecLike.runTests$(PropSpecLike.scala:228)
[spire] [info]   at org.scalatest.PropSpec.runTests(PropSpec.scala:874)
[spire] [info]   at org.scalatest.Suite.run(Suite.scala:1147)
[spire] [info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[spire] [info]   at org.scalatest.PropSpec.org$scalatest$PropSpecLike$$super$run(PropSpec.scala:874)
[spire] [info]   at org.scalatest.PropSpecLike.$anonfun$run$1(PropSpecLike.scala:233)
[spire] [info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[spire] [info]   at org.scalatest.PropSpecLike.run(PropSpecLike.scala:233)
[spire] [info]   at org.scalatest.PropSpecLike.run$(PropSpecLike.scala:232)
[spire] [info]   at org.scalatest.PropSpec.run(PropSpec.scala:874)
[spire] [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[spire] [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[spire] [info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[spire] [info]   at sbt.TestRunner.run(TestFramework.scala:85)
[spire] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[spire] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[spire] [info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[spire] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[spire] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[spire] [info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[spire] [info]   at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
[spire] [info]   at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
[spire] [info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[spire] [info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[spire] [info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[spire] [info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[spire] [info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[spire] [info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[spire] [info]   at sbt.Execute.work(Execute.scala:237)
[spire] [info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[spire] [info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[spire] [info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[spire] [info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[spire] [info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[spire] [info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[spire] [info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[spire] [info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[spire] [info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[spire] [info]   at java.lang.Thread.run(Thread.java:745)
[spire] [info]   Cause: org.scalatest.exceptions.TestFailedException: (80/43x⁹⁵ + x⁹¹ + 1/4x⁸⁹ - 1/8x⁸⁴ - 34x⁸² + x⁸⁰ + 1/7x⁷⁸ - 52/7x⁷⁴ + 7/2x⁷³ + 7/54x⁷¹ - 1/53x⁶⁹ + 1/2x⁶⁸ + 1/8x⁶⁴ + 1/4x⁶¹ - 124/5x⁵³ - 4241/690x⁴⁸ - 37/30x⁴⁷ + 1/21x⁴² + x³⁸ + 29x³⁶ + x²³ + 36x²¹ - 13x¹⁹ - 229/520x¹⁶ + 43/35x¹¹ + 371/624x¹⁰ - 1062/217x⁹ + 33/46x³ + 69x² + 95015759/19888440x + 77125717/602140) was not equal to (80/43x⁹⁵ + x⁹¹ + 1/4x⁸⁹ - 1/8x⁸⁴ - 34x⁸² + x⁸⁰ + 1/7x⁷⁸ - 52/7x⁷⁴ + 7/2x⁷³ + 7/54x⁷¹ - 1/53x⁶⁹ + 1/2x⁶⁸ + 1/8x⁶⁴ + 1/4x⁶¹ - 124/5x⁵³ - 4241/690x⁴⁸ - 37/30x⁴⁷ + 1/21x⁴² + x³⁸ + 29x³⁶ + x²³ + 36x²¹ - 13x¹⁹ - 229/520x¹⁶ + 43/35x¹¹ + 371/624x¹⁰ - 1062/217x⁹ + 33/46x³ + 69x² + 95015759/19888440x + 77125717/602140)
[spire] [info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[spire] [info]   at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
[spire] [info]   at spire.math.PolynomialCheck.$anonfun$runTest$4(PolynomialTest.scala:97)
[spire] [info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.liftedTree7$1(GeneratorDrivenPropertyChecks.scala:838)
[spire] [info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.$anonfun$forAll$1(GeneratorDrivenPropertyChecks.scala:837)
[spire] [info]   at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
[spire] [info]   at org.scalacheck.Prop$.$anonfun$forAllShrink$2(Prop.scala:712)
[spire] [info]   at org.scalacheck.Prop$.secure(Prop.scala:456)
[spire] [info]   at org.scalacheck.Prop$.result$1(Prop.scala:712)
[spire] [info]   at org.scalacheck.Prop$.$anonfun$forAllShrink$1(Prop.scala:749)
[spire] [info]   at org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:292)
[spire] [info]   at org.scalacheck.PropFromFun.apply(Prop.scala:22)
[spire] [info]   at org.scalacheck.Test$.workerFun$1(Test.scala:294)
[spire] [info]   at org.scalacheck.Test$.$anonfun$check$1(Test.scala:323)
[spire] [info]   at org.scalacheck.Test$.$anonfun$check$1$adapted(Test.scala:323)
[spire] [info]   at org.scalacheck.Platform$.runWorkers(Platform.scala:40)
[spire] [info]   at org.scalacheck.Test$.check(Test.scala:323)
[spire] [info]   at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:88)
[spire] [info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll(GeneratorDrivenPropertyChecks.scala:851)
[spire] [info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll$(GeneratorDrivenPropertyChecks.scala:827)
[spire] [info]   at spire.math.PolynomialCheck.forAll(PolynomialTest.scala:53)
[spire] [info]   at spire.math.PolynomialCheck.$anonfun$runTest$3(PolynomialTest.scala:97)
[spire] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[spire] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[spire] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[spire] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[spire] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[spire] [info]   at org.scalatest.PropSpecLike$$anon$1.apply(PropSpecLike.scala:186)
[spire] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[spire] [info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[spire] [info]   at org.scalatest.PropSpec.withFixture(PropSpec.scala:874)
[spire] [info]   at org.scalatest.PropSpecLike.invokeWithFixture$1(PropSpecLike.scala:184)
[spire] [info]   at org.scalatest.PropSpecLike.$anonfun$runTest$1(PropSpecLike.scala:196)
[spire] [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[spire] [info]   at org.scalatest.PropSpecLike.runTest(PropSpecLike.scala:196)
[spire] [info]   at org.scalatest.PropSpecLike.runTest$(PropSpecLike.scala:178)
[spire] [info]   at org.scalatest.PropSpec.runTest(PropSpec.scala:874)
[spire] [info]   at org.scalatest.PropSpecLike.$anonfun$runTests$1(PropSpecLike.scala:229)
[spire] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[spire] [info]   at scala.collection.immutable.List.foreach(List.scala:378)
[spire] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[spire] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[spire] [info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[spire] [info]   at org.scalatest.PropSpecLike.runTests(PropSpecLike.scala:229)
[spire] [info]   at org.scalatest.PropSpecLike.runTests$(PropSpecLike.scala:228)
[spire] [info]   at org.scalatest.PropSpec.runTests(PropSpec.scala:874)
[spire] [info]   at org.scalatest.Suite.run(Suite.scala:1147)
[spire] [info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[spire] [info]   at org.scalatest.PropSpec.org$scalatest$PropSpecLike$$super$run(PropSpec.scala:874)
[spire] [info]   at org.scalatest.PropSpecLike.$anonfun$run$1(PropSpecLike.scala:233)
[spire] [info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[spire] [info]   at org.scalatest.PropSpecLike.run(PropSpecLike.scala:233)
[spire] [info]   at org.scalatest.PropSpecLike.run$(PropSpecLike.scala:232)
[spire] [info]   at org.scalatest.PropSpec.run(PropSpec.scala:874)
[spire] [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[spire] [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[spire] [info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[spire] [info]   at sbt.TestRunner.run(TestFramework.scala:85)
[spire] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[spire] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[spire] [info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[spire] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[spire] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[spire] [info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[spire] [info]   at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
[spire] [info]   at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
[spire] [info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[spire] [info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[spire] [info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[spire] [info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[spire] [info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[spire] [info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[spire] [info]   at sbt.Execute.work(Execute.scala:237)
[spire] [info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[spire] [info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[spire] [info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[spire] [info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[spire] [info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[spire] [info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[spire] [info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[spire] [info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[spire] [info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[spire] [info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by denisrosset** [comment]
Thanks for the report. There are indeed transient failures on the polynomial code.

**Comment by SethTisue** [comment]
polynomial failure seen again at https://scala-ci.typesafe.com/view/All/job/scala-2.12.x-integrate-community-build/1954/consoleFull

**Comment by SethTisue** [comment]
see also #608

**Comment by SethTisue** [comment]
polynomial failure again: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2010/consoleFull

**Comment by denisrosset** [comment]
Should be addressed by #653

**Comment by SethTisue** [comment]
can #653 be reviewed? this failed again in the community build (https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2319/consoleFull)

**Comment by SethTisue** [comment]
#653 has been merged. optimistically closing
