### ISSUE TITLE
Rational.limitToInt doesn't terminate for 1 and -1

### ISSUE THREAD

**Issue by pedropramos** [non/spire#585]
The following inputs lead to infinite recursion
```
Rational(-1).limitToInt
```
```
Rational(1).limitToInt
```

**Comment by pedropramos** [comment]
In case it's any help, after compiling with `-g:notailcalls`, this yields the following stack trace:
```
scala> Rational(-1).limitToInt
java.lang.StackOverflowError
  at spire.math.package$.gcd(package.scala:284)
  at spire.math.Rational$.build0$1(Rational.scala:240)
  at spire.math.Rational$.apply(Rational.scala:247)
  at spire.math.Rational$.apply(Rational.scala:264)
  at spire.math.Rational.closest$1(Rational.scala:164)
  at spire.math.Rational.closest$1(Rational.scala:173)
  at spire.math.Rational.closest$1(Rational.scala:173)
  at spire.math.Rational.closest$1(Rational.scala:173)
  ...
```

**Comment by tixxit** [comment]
Thanks for reporting!

**Comment by tixxit** [comment]
I've been investigating and this actually isn't infinite recursion, but rather just very slow convergence. I believe I've implemented a fix. Will make sure existing tests pass and exercise this stuff, but it should make convergence quite quick in all cases.
